version: '3'

services:
  naala:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx:stable-alpine
    container_name: naala
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
